In [ ]:
import numpy as np

In [ ]:
# MSE

def mean_squared_error(y, t):
  return 0.5*np.sum((y-t)**2)

In [ ]:
# CrossEntropyError

def cross_entropy_error(y, t):
  delta=1e-7
  return -np.sum(t*np.log(y+delta))

In [ ]:
# CEE for Batch
def cross_entropy_error_batch(y, t):
  if y.ndim==1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, y.size)
  
  batch_size=y.shape[0]
  delta = 1e-7
  return -np.sum(t * np.log(y+delta)) / batch_size

In [ ]:
# 수치 미분

def numerical_diff(f, x):
  h = 1e-4
  return (f(x+h) - f(x-h)) / (2*h)

In [ ]:
# 편미분과 기울기

def numerical_gradient(f, x):
  h = 1e-4
  grad = np.zeros_like(x)

  for idx in range(x.size):
    print(x.size)
    print(x)
    print(idx)
    print(x[idx])
    tmp_val = x[idx]

    '''
    # f(x+h)

    # f(x-h)
    
    '''

  return grad

In [ ]:
# GD

def gradient_descent(f, init_x, lr=0.01, step_num=100):
  x = init_x
  for i in range(step_num):
    grad = numerical_gradient(f, x)
    x -= lr*grad
  return x

In [ ]:
def function(x):
  return x[0]**2 + x[1]**2

init_x = np.array([-3.0, 4.0])
gradient_descent(function, init_x=init_x, lr=0.1, step_num=100)

In [ ]:
class simpleNet:
  def __init__(self):
    self.W = np.random.randn(2, 3)

  def predict(self, x):
    return x @ self.W

  def softmax(self, x):
    c = np.max(x)
    exp_x = np.exp(x - c)
    sum_exp_x = np.sum(exp_x)
    return exp_x / sum_exp_x

  def loss(self, x, t):
    z = self.predict(x)
    y = self.softmax(z)
    loss = cross_entropy_error(y, t)
    return loss

In [ ]:
net = simpleNet()
net.W

array([[-1.83719583, -0.16515208,  1.7535606 ],
       [ 1.26246935, -1.53427656,  0.38942022]])

In [ ]:
x = np.array([0.6, 0.9])
p = net.predict(x)
p

array([ 0.03390491, -1.47994015,  1.40261456])

In [ ]:
np.argmax(p)

2

In [ ]:
t = np.array([0, 0, 1])
net.loss(x, t)

0.270352598868895

In [ ]:
def numerical_gradient(f, x):
  h = 1e-4  # 0.0001
  grad = np.zeros_like(x)

  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite']) # 배열 반복
  while not it.finished:
    print(it.multi_index) # 출력 확인
    idx = it.multi_index

    '''
    

    '''
    it.iternext()

  return grad

In [ ]:
f = lambda w:net.loss(x, t)
dW = numerical_gradient(f, net.W)
dW

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


array([[ 0.11649719,  0.02563663, -0.14213382],
       [ 0.17474578,  0.03845494, -0.21320072]])

In [ ]:
def f(W):
  return net.loss(x, t)
dW = numerical_gradient(f, net.W)
dW

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


array([[ 0.11649719,  0.02563663, -0.14213382],
       [ 0.17474578,  0.03845494, -0.21320072]])

In [ ]:
class TwoLayerNet:
  # 초기화를 수행한다.
  def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):
    # 가중치 초기화
    self.params = {}
    self.params['W1'] = weight_init_std * np.random.randn(input_size, hidden_size)
    self.params['b1'] = np.zeros(hidden_size)
    self.params['W2'] = weight_init_std * np.random.randn(hidden_size, output_size)
    self.params['b2'] = np.zeros(output_size)

  def sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def softmax(self, x):
    c = np.max(x)
    exp_x = np.exp(x - c)
    sum_exp_x = np.sum(exp_x)
    return exp_x / sum_exp_x

  # 예측(추론)을 수행한다.
  def predict(self, x):
    W1, W2 = self.params['W1'], self.params['W2']
    b1, b2 = self.params['b1'], self.params['b2']

    a1 = np.dot(x, W1) + b1
    z1 = self.sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    y = self.softmax(a2)

    return y

  def cross_entropy_error(self, y, t):
      if y.ndim == 1:
          t = t.reshape(1, t.size)
          y = y.reshape(1, y.size)
          
      # 훈련 데이터가 원-핫 벡터라면 정답 레이블의 인덱스로 반환
      if t.size == y.size:
          t = t.argmax(axis=1)
              
      batch_size = y.shape[0]
      return -np.sum(np.log(y[np.arange(batch_size), t])) / batch_size

  # 손실 함수의 값을 구한다.
  # x : 입력데이터, t : 정답 레이블
  def loss(self, x, t):
    y = self.predict(x)

    return self.cross_entropy_error(y, t)

  # 정확도를 구한다.
  def accuracy(self, x, t):
    y = self.predict(x)
    y = np.argmax(y, axis=1)
    t = np.argmax(t, axis=1)

    accuracy = np.sum(y == t) / float(x.shape[0])
    return accuracy

  def numerical_gradient(self, f, x):
    h = 1e-4  # 0.0001
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
      idx = it.multi_index

      '''
      
      '''

      it.iternext()

    return grad

  # 가중치 매개변수의 기울기를 구한다.
  def numerical_gradient_all(self, x, t):
    loss_W = lambda W: self.loss(x, t)

    grads = {}
    grads['W1'] = self.numerical_gradient(loss_W, self.params['W1'])
    grads['b1'] = self.numerical_gradient(loss_W, self.params['b1'])
    grads['W2'] = self.numerical_gradient(loss_W, self.params['W2'])
    grads['b2'] = self.numerical_gradient(loss_W, self.params['b2'])

    return grads

In [ ]:
net = TwoLayerNet(input_size=784, hidden_size=100, output_size=10)
print(net.params['W1'].shape)  # (784, 100)
print(net.params['b1'].shape)  # (100,)
print(net.params['W2'].shape)  # (100, 10)
print(net.params['b2'].shape)  # (10,)

x = np.random.rand(100, 784)  # 더미 입력 데이터(100장 분량)
t = np.random.rand(100, 10)   # 더미 정답 레이블(100장 분량)

%time grads = net.numerical_gradient_all(x, t)  # 기울기 계산
# 주의 : 실행하는데 아주 오래걸림
print(grads['W1'].shape)  # (784, 100)
print(grads['b1'].shape)  # (100,)
print(grads['W2'].shape)  # (100, 10)
print(grads['b2'].shape)  # (10,)

In [ ]:
!unzip dataset03.zip

Archive:  /content/dataset03.zip
replace dataset/__init__.py? [y]es, [n]o, [A]ll, [N]one, [r]ename: yA
  inflating: dataset/__init__.py     
replace dataset/__pycache__/__init__.cpython-37.pyc? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: dataset/__pycache__/__init__.cpython-37.pyc  
  inflating: dataset/__pycache__/mnist.cpython-37.pyc  
  inflating: dataset/cactus.png      
  inflating: dataset/cactus_gray.png  
  inflating: dataset/mnist.pkl       
  inflating: dataset/mnist.py        
  inflating: dataset/t10k-images-idx3-ubyte.gz  
  inflating: dataset/t10k-labels-idx1-ubyte.gz  
  inflating: dataset/train-images-idx3-ubyte.gz  
  inflating: dataset/train-labels-idx1-ubyte.gz  
  inflating: sample_weight.pkl       


In [ ]:
from dataset.mnist import load_mnist
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

In [ ]:
# Hyperparameter
iters_num = 1000  # 반복횟수
train_size = x_train.shape[0]
batch_size = 100  # 미니배치 크기
learning_rate = 0.1
network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

train_loss_list = []
train_acc_list = []
test_acc_list = []

# 1에폭당 반복 수
iter_per_epoch = max(train_size / batch_size, 1)

In [ ]:
from tqdm.auto import tqdm # progress bar

for i in tqdm(range(iters_num)):
  # print(i) # Progress Bar를 사용하므로 iter를 출력할 필요 없음

  # 미니배치 획득
  batch_mask = np.random.choice(train_size, batch_size)
  x_batch = x_train[batch_mask]
  t_batch = t_train[batch_mask]

  # 기울기 계산
  grad = network.numerical_gradient_all(x_batch, t_batch)

  # 매개변수 갱신
  for key in ('W1', 'b1', 'W2', 'b2'): 
    network.params[key] -= learning_rate * grad[key]

  # 학습 경과 기록
  loss = network.loss(x_batch, t_batch)
  train_loss_list.append(loss)

  # 1에폭 당 정확도 계산
  if i % iter_per_epoch == 0:
    train_acc = network.accuracy(x_train, t_train)
    test_acc = network.accuracy(x_test, t_test)
    train_acc_list.append(train_acc)
    test_acc_list.append(test_acc)
    print("train acc, test acc | "+ str(train_acc) + ", " + str(test_acc))

## 아주 오랜 시간이 걸리므로, 결과가 나올 필요 없음

  0%|          | 0/1000 [00:00<?, ?it/s]

train acc, test acc | 0.09736666666666667, 0.0982
train acc, test acc | 0.11236666666666667, 0.1135
