# Torch Basic

## numpy

In [4]:
import numpy as np

### 1D

In [11]:
t = np.array([3, 5, 7])
print(t)

array([3, 5, 7])

In [9]:
t.ndim

1

In [10]:
t.shape

(3,)

### 2D

In [12]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]] )
t

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
t.ndim

2

In [14]:
t.shape

(3, 3)

## torch

In [1]:
import torch

In [4]:
scalar = torch.tensor(5)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [15]:
scalar

tensor(5)

In [16]:
vector

tensor([1, 2, 3])

In [17]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
tensor

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [19]:
scalar + vector

tensor([6, 7, 8])

In [20]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [21]:
# matrix.matmul(matrix)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [24]:
matrix.matmul(matrix.transpose(1,0))

tensor([[14, 32],
        [32, 77]])

## basic operations

In [27]:
# Mean
a = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print(a.mean())
print(a.mean(dim=0)) # dim=0 is columns
print(a.mean(dim=1)) # dim=1 is rows


tensor(5.5000)
tensor([4., 5., 6., 7.])
tensor([1.5000, 5.5000, 9.5000])


In [2]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [3]:
x.squeeze()

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [5]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Perform view, reshape, squeeze, unsqueeze, and cat operations
view_result = tensor.view(-1)  # Fill in the blank
reshape_result = tensor.reshape(2)  # Fill in the blank
unsqueeze_result = tensor.unsqueeze(0)  # Fill in the blank
cat_result = torch.cat((tensor_a, tensor_b), dim=0)  # Fill in the blank


In [6]:
print("\nView Result:", view_result)
print("\nReshape Result:\n", reshape_result)
print("\nUnsqueeze Result:\n", unsqueeze_result)
print("\nConcatenation Result:\n", cat_result)


View Result: tensor([1, 2, 3, 4, 5, 6, 7, 8])

Reshape Result:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Unsqueeze Result:
 tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

Concatenation Result:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
